httpPort: 13000
MetricPort: 5858
appName: game
log:
  level: DEBUG
db:
  mongo:
    url: mongodb://8.130.44.1:27017
    userName: chess
    password: 5211314
    minPoolSize: 10
    maxPoolSize: 100
    db: chess
  redis:
    addr: 8.130.44.1:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7
