httpPort: 13000
MetricPort: 5857
appName: hall
log:
  level: DEBUG
db:
  mongo:
    url: mongodb://8.130.44.1:27017
    userName: chess
    password: 5211314
    minPoolSize: 10
    maxPoolSize: 100
    db: chess
  redis:
    addr: 8.130.44.1:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7
domain:
  user:
    name: user/v1
    loadBalance: true
etcd:
  addrs:
    - 127.0.0.1:2379
  rwTimeout: 3
  dialTimeout: 3
services:
  connector:
    id: connector-1
    clientHost: 127.0.0.1
    clientPort: 12000